package wotr.mapping;

import java.util.HashMap;
import java.util.Map;

/**
 * RegionMapper - Maps Game.java Area indices to database Region IDs
 * 
 * PROOF OF CONCEPT: Starting with map regions only
 * 
 * This maps the ~104 board areas in Game.java to the 104 regions in the database
 */
public class RegionMapper {
    private static RegionMapper instance;
    
    // Area index → Database Region ID (integer)
    private Map<Integer, String> areaToRegionId;
    
    // Database Region ID → Area index  
    private Map<String, Integer> regionIdToArea;
    
    private RegionMapper() {
        this.areaToRegionId = new HashMap<>();
        this.regionIdToArea = new HashMap<>();
        initializeRegionMappings();
    }
    
    public static synchronized RegionMapper getInstance() {
        if (instance == null) {
            instance = new RegionMapper();
        }
        return instance;
    }
    
    /**
     * Map Game.java area indices to database region IDs
     * 
     * COMPLETE MAPPINGS: All 105 map regions from Game.java areas[] to database regions table
     * Generated by CompleteRegionMapping.java from messages.properties
     * Fixed name mismatches manually (Grey Havens, Dimrill Dale, etc.)
     * Added Tower Hills (region 69) after it was added to metadata.json
     * 
     * Database region IDs are integers (1-105) from regions table (105 total)
     * Area indices are from Game.java areas[] array (0-211)
     */
    private void initializeRegionMappings() {
        // All map regions (105 total)
        mapRegion(0, "54");    // Minhiriath
        mapRegion(1, "85");    // South Ered Luin
        mapRegion(2, "9");     // Cardolan
        mapRegion(3, "43");    // Harlindon
        mapRegion(4, "92");    // Grey Havens (The Grey Havens in messages)
        mapRegion(5, "38");    // Forlindon
        mapRegion(6, "69");    // Tower Hills
        mapRegion(7, "93");    // The Shire
        mapRegion(8, "30");    // Ered Luin
        mapRegion(9, "74");    // Old Forest
        mapRegion(10, "64");   // North Ered Luin
        mapRegion(11, "27");   // Enedwaith
        mapRegion(12, "4");    // Arnor
        mapRegion(13, "8");    // Buckland
        mapRegion(14, "3");    // Angmar
        mapRegion(15, "62");   // North Downs
        mapRegion(16, "91");   // Tharbad
        mapRegion(17, "31");   // Ettenmoors
        mapRegion(18, "7");    // Bree
        mapRegion(19, "57");   // Mount Gram
        mapRegion(20, "98");   // Weather Hills
        mapRegion(21, "18");   // Druwaith Iaur
        mapRegion(22, "83");   // South Downs
        mapRegion(23, "1");    // Andrast
        mapRegion(24, "94");   // Trollshaws
        mapRegion(25, "2");    // Anfalas
        mapRegion(26, "63");   // North Dunland
        mapRegion(27, "81");   // Rivendell
        mapRegion(28, "46");   // Hollin
        mapRegion(29, "29");   // Erech
        mapRegion(30, "84");   // South Dunland
        mapRegion(31, "36");   // Fords of Bruinen
        mapRegion(32, "39");   // Gap of Rohan
        mapRegion(33, "45");   // High Pass
        mapRegion(34, "40");   // Gladden Fields
        mapRegion(35, "56");   // Moria
        mapRegion(36, "16");   // Drimill Dale (Dimrill Dale in messages)
        mapRegion(37, "51");   // Lorien
        mapRegion(38, "78");   // Parth Celebrant
        mapRegion(39, "33");   // Fangorn
        mapRegion(40, "76");   // Orthanc
        mapRegion(41, "37");   // Fords of Isen
        mapRegion(42, "14");   // Dol Amroth
        mapRegion(43, "26");   // Edoras
        mapRegion(44, "58");   // Mount Gundabad
        mapRegion(45, "44");   // Helm's Deep
        mapRegion(46, "49");   // Lamedon
        mapRegion(47, "99");   // Westemnet
        mapRegion(48, "79");   // Pelargir
        mapRegion(49, "95");   // Umbar
        mapRegion(50, "35");   // Folde
        mapRegion(51, "19");   // Eagles' Eyrie
        mapRegion(52, "50");   // Lossarnach
        mapRegion(53, "41");   // Goblin's Gate
        mapRegion(54, "20");   // Eastemnet
        mapRegion(55, "103");  // West Harondor
        mapRegion(56, "32");   // Evendim
        mapRegion(57, "73");   // Old Ford
        mapRegion(58, "10");   // Carrock
        mapRegion(59, "17");   // Druadan Forest
        mapRegion(60, "80");   // Rhosgobel
        mapRegion(61, "60");   // Near Harad
        mapRegion(62, "67");   // Northern Mirkwood
        mapRegion(63, "15");   // Dol Guldur
        mapRegion(64, "65");   // Northern Anduin Vale (North Anduin Vale in messages)
        mapRegion(65, "102");  // Western Mirkwood
        mapRegion(66, "100");  // Western Brown Lands
        mapRegion(67, "101");  // Western Emyn Muil
        mapRegion(68, "24");   // East Harondor
        mapRegion(69, "82");   // South Anduin Vale
        mapRegion(70, "105");  // Woodland Realms (Woodland Realm in messages)
        mapRegion(71, "13");   // Dead Marshes
        mapRegion(72, "70");   // North Ithilien
        mapRegion(73, "77");   // Osgiliath
        mapRegion(74, "53");   // Minas Tirith
        mapRegion(75, "89");   // South Ithilien
        mapRegion(76, "75");   // Old Forest Road
        mapRegion(77, "59");   // Narrows of the Forest
        mapRegion(78, "21");   // Eastern Brown Lands
        mapRegion(79, "23");   // Eastern Mirkwood
        mapRegion(80, "104");  // Withered Heath
        mapRegion(81, "87");   // Southern Mirkwood
        mapRegion(82, "28");   // Erebor
        mapRegion(83, "68");   // Northern Rhovanion
        mapRegion(84, "22");   // Eastern Emyn Muil
        mapRegion(85, "34");   // Far Harad
        mapRegion(86, "52");   // Minas Morgul
        mapRegion(87, "12");   // Dale
        mapRegion(88, "72");   // Nurn
        mapRegion(89, "61");   // Noman-Lands
        mapRegion(90, "47");   // Iron Hills
        mapRegion(91, "55");   // Morannon
        mapRegion(92, "88");   // Southern Rhovanion
        mapRegion(93, "11");   // Dagorlad
        mapRegion(94, "42");   // Gorgoroth
        mapRegion(95, "48");   // Khand
        mapRegion(96, "6");    // Barad-Dur
        mapRegion(97, "96");   // Vale of Carnen (Vale of the Carnen in messages)
        mapRegion(98, "5");    // Ash Mountains
        mapRegion(99, "97");   // Vale of Celdium (Vale of the Celduin in messages)
        mapRegion(100, "86");  // Southern Dorwinion
        mapRegion(101, "25");  // East Rhun
        mapRegion(102, "66");  // Northern Dorwinion
        mapRegion(103, "90");  // South Rhun
        mapRegion(104, "71");  // North Rhun
        
        System.out.println("[RegionMapper] Initialized with " + areaToRegionId.size() + " complete region mappings");
    }
    
    /**
     * Add bidirectional mapping
     */
    private void mapRegion(int areaIndex, String regionId) {
        areaToRegionId.put(areaIndex, regionId);
        regionIdToArea.put(regionId, areaIndex);
    }
    
    /**
     * Get database region ID for an area index
     * @return region ID (as string) or null if not a map region
     */
    public String getRegionId(int areaIndex) {
        return areaToRegionId.get(areaIndex);
    }
    
    /**
     * Get area index for a database region ID
     * @return area index or -1 if not found
     */
    public int getAreaIndex(String regionId) {
        return regionIdToArea.getOrDefault(regionId, -1);
    }
    
    /**
     * Check if this area is a map region
     */
    public boolean isMapRegion(int areaIndex) {
        return areaToRegionId.containsKey(areaIndex);
    }
    
    /**
     * Get all mapped region IDs
     */
    public java.util.Set<String> getAllRegionIds() {
        return regionIdToArea.keySet();
    }
    
    /**
     * Get count of mapped regions
     */
    public int getMappedRegionCount() {
        return areaToRegionId.size();
    }
}
