package wotr;

import java.awt.Button;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.image.ImageObserver;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/* renamed from: ChooseFSP */
public class ChooseFSP {
    static JRadioButton Boromir = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Boromir2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static boolean CouncilChosen = false;
    static JRadioButton Gandalf1 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Gandalf2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Gimli = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Gimli2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Legolas = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Legolas2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Merry = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Merry2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Pippin = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Pippin2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Strider = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    static JRadioButton Strider2 = new JRadioButton(new ImageIcon("expansion2/images/unselected-E.png"));
    Game game;

    public void display(Game newGame) {
        Frame frm = new JFrame();
        this.game = newGame;
        frm.setSize(581, 408);
        frm.setUndecorated(true);
        frm.setAlwaysOnTop(true);
        frm.setLocation((Game.win.getWidth() - 581) / 2, (Game.win.getHeight() - 408) / 2);
        frm.setVisible(true);
        final Button Submit = new Button(Messages.getString("ChooseFSP.14"));
        Gandalf1.setActionCommand("Gandalf");
        Gandalf1.setOpaque(false);
        Gandalf1.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Gandalf1.setSelected(true);
        Gandalf2.setOpaque(false);
        Gandalf2.setActionCommand("Gandalf2");
        Gandalf2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Boromir.setOpaque(false);
        Boromir.setActionCommand("Boromir");
        Boromir.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Boromir2.setOpaque(false);
        Boromir2.setActionCommand("Boromir2");
        Boromir2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Strider.setOpaque(false);
        Strider.setActionCommand("Strider");
        Strider.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Strider2.setOpaque(false);
        Strider2.setActionCommand("Strider2");
        Strider2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Legolas.setOpaque(false);
        Legolas.setActionCommand("Legolas");
        Legolas.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Legolas2.setOpaque(false);
        Legolas2.setActionCommand("Legolas2");
        Legolas2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Merry.setOpaque(false);
        Merry.setActionCommand("Merry");
        Merry.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Merry2.setOpaque(false);
        Merry2.setActionCommand("Merry2");
        Merry2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Gimli.setOpaque(false);
        Gimli.setActionCommand("Gimli");
        Gimli.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Gimli2.setOpaque(false);
        Gimli2.setActionCommand("Gimli2");
        Gimli2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Pippin.setOpaque(false);
        Pippin.setActionCommand("Pippin");
        Pippin.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        Pippin2.setOpaque(false);
        Pippin2.setActionCommand("Pippin2");
        Pippin2.setSelectedIcon(new ImageIcon("expansion2/images/selected-E.png"));
        JPanel contentPane = new JPanel() {
            /* access modifiers changed from: protected */
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(new ImageIcon(Messages.getLanguageLocation("images/FSPChoose.png")).getImage(), 0, 0, (ImageObserver) null);
                Submit.setBounds(530, 357, 40, 40);
                ChooseFSP.Gandalf1.setBounds(93, 70, 14, 14);
                ChooseFSP.Gandalf2.setBounds(93, 89, 14, 14);
                ChooseFSP.Boromir.setBounds(350, 192, 14, 14);
                ChooseFSP.Boromir2.setBounds(350, 211, 14, 14);
                ChooseFSP.Strider.setBounds(93, 192, 14, 14);
                ChooseFSP.Strider2.setBounds(93, 211, 14, 14);
                ChooseFSP.Legolas.setBounds(93, 267, 14, 14);
                ChooseFSP.Legolas2.setBounds(93, 286, 14, 14);
                ChooseFSP.Merry.setBounds(349, 265, 14, 14);
                ChooseFSP.Merry2.setBounds(350, 284, 14, 14);
                ChooseFSP.Gimli.setBounds(93, 340, 14, 14);
                ChooseFSP.Gimli2.setBounds(93, 359, 14, 14);
                ChooseFSP.Pippin.setBounds(349, 338, 14, 14);
                ChooseFSP.Pippin2.setBounds(349, 357, 14, 14);
            }
        };
        contentPane.setSize(581, 408);
        frm.add(contentPane);
        Submit.setBounds(530, 357, 40, 40);
        contentPane.add(Submit);
        ButtonGroup group = new ButtonGroup();
        group.add(Gandalf1);
        group.add(Gandalf2);
        contentPane.add(Gandalf1);
        contentPane.add(Gandalf2);
        ButtonGroup group2 = new ButtonGroup();
        group2.add(Boromir);
        group2.add(Boromir2);
        contentPane.add(Boromir);
        contentPane.add(Boromir2);
        ButtonGroup group3 = new ButtonGroup();
        group3.add(Strider);
        group3.add(Strider2);
        contentPane.add(Strider);
        contentPane.add(Strider2);
        ButtonGroup group4 = new ButtonGroup();
        group4.add(Legolas);
        group4.add(Legolas2);
        contentPane.add(Legolas);
        contentPane.add(Legolas2);
        ButtonGroup group5 = new ButtonGroup();
        group5.add(Merry);
        group5.add(Merry2);
        contentPane.add(Merry);
        contentPane.add(Merry2);
        ButtonGroup group6 = new ButtonGroup();
        group6.add(Gimli);
        group6.add(Gimli2);
        contentPane.add(Gimli);
        contentPane.add(Gimli2);
        ButtonGroup group7 = new ButtonGroup();
        group7.add(Pippin);
        group7.add(Pippin2);
        contentPane.add(Pippin);
        contentPane.add(Pippin2);
        Gandalf1.addActionListener(new RadioButtonHandler(this));
        Gandalf2.addActionListener(new RadioButtonHandler(this));
        Boromir.addActionListener(new RadioButtonHandler(this));
        Boromir2.addActionListener(new RadioButtonHandler(this));
        Strider.addActionListener(new RadioButtonHandler(this));
        Strider2.addActionListener(new RadioButtonHandler(this));
        Legolas.addActionListener(new RadioButtonHandler(this));
        Legolas2.addActionListener(new RadioButtonHandler(this));
        Merry.addActionListener(new RadioButtonHandler(this));
        Merry2.addActionListener(new RadioButtonHandler(this));
        Gimli.addActionListener(new RadioButtonHandler(this));
        Gimli2.addActionListener(new RadioButtonHandler(this));
        Pippin.addActionListener(new RadioButtonHandler(this));
        Pippin2.addActionListener(new RadioButtonHandler(this));
        Submit.addActionListener(new ButtonHandler(frm, this.game, this));
        frm.setVisible(true);
    }
}
